# Generated by Django 5.2 on 2025-05-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_adoption_phone_number_alter_pet_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shelter_logo/'),
        ),
    ]
