# Generated by Django 5.2 on 2025-05-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_pet_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
