# Generated by Django 5.2 on 2025-05-02 23:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone', models.CharField(default='0000000000', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(120)])),
                ('help_type', models.CharField(choices=[('money', 'Money'), ('help', 'Cleaning & Animal Care')], max_length=10)),
                ('help_description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('donation_date', models.DateField(blank=True, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption.shelter')),
            ],
        ),
    ]
