# Generated by Django 5.2 on 2025-05-03 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0005_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='availability',
            field=models.CharField(blank=True, choices=[('1-5', '1-5 hours'), ('5-10', '5-10 hours'), ('10-20', '10-20 hours'), ('20+', '20+ hours')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='city',
            field=models.CharField(default='Sousse', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='help_type',
            field=models.CharField(choices=[('money', 'Financial Donation'), ('help', 'Volunteer Time (Cleaning & Animal Care)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', "Phone number must be entered in the format: '+999999999'.")]),
        ),
    ]
